name: Bug report
description: Report a reproducible bug
title: "fix: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Arquivado
        Este repositório está arquivado e permanece público apenas para fins de estudo.
        Não há garantia de resposta, triagem, revisão ou correção.
  - type: markdown
    attributes:
      value: "Please provide enough details for reproducibility."
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Short problem description
      placeholder: What is broken?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Include exact commands and interactions
      placeholder: |
        1. Run ...
        2. Click ...
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: Node, npm, OS, browser
    validations:
      required: true
